### ISSUE TITLE
在flexdashboard的编码问题

### ISSUE THREAD

**Issue by feng5** [taiyun/recharts#33]
```
x = data.frame(dt=1:6, buymoney=1:6, ordertype=c('充值','充值','充值','提现','提现', '提现'))
eBar(dat= x, xvar=~dt, yvar=~buymoney, series=~ordertype)
```
同一段代码在Rstudio的viewer中正常显示中文，但是在rmarkdown的flexdashboard格式里中文乱码了
```
title: 'test'
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
runtime: shiny
```
